services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
